# Generated by Django 5.0 on 2024-01-22 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_products_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
