# Generated by Django 5.0 on 2024-01-26 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.CharField(default='admin@gmail.com', max_length=200),
            preserve_default=False,
        ),
    ]
