# Generated by Django 5.0 on 2024-01-26 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_order_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.CharField(default='none', max_length=1000),
            preserve_default=False,
        ),
    ]
